from cube_model import Cube_model

cube = Cube_model()
print(cube.sides)
cube.rotate_r2()
cube.rotate_f2()
cube.rotate_r2()
cube.rotate_u()
cube.rotate_r2()
cube.rotate_b2()
cube.rotate_d()
cube.rotate_u2()
cube.rotate_reverse_u()
cube.rotate_l2()
print()
print(cube.sides)