from cube_model import Cube_model

cube = Cube_model()
print(cube.sides)
cube.rotate_f2()
cube.rotate_d()
print()
print(cube.sides)
cube.rotate_l()
print()
print(cube.sides)
cube.rotate_reverse_d()
print()
print(cube.sides)
cube.rotate_reverse_b()
print()
print(cube.sides)